project:
  type: website

website:
  title: "Data PMSI"
  description: "Formations PMSI MCO, PMSI SSR avec R et tidyverse"
  navbar:
    background: "#447099"
    left: 
      - href: planning.qmd
        text: "Planning des formations"
      - href: pedagogie.qmd
        text: "Pédagogie"
      - href: prestation.qmd
        text: "Prestations"
    right: 
      - text: "Jeux de données"
        menu:
          - href: "dataset_mco.qmd"
            text: "Jeux PMSI MCO"
          - href: "dataset_ssr.qmd"
            text: "Jeux PMSI SSR"
          - href: "dataset_psy.qmd"
            text: "Jeux PMSI PSY"
      - icon: github
        href: https://github.com/denisGustin/datapmsi
  sidebar: 
    style: docked
    contents: 
      - href: formations/pmsi_initiation.qmd
        text: "Le PMSI avec R"
      - section: "Formations MCO"
        contents: 
          - href: formations/pmsi_mco_requete.qmd
            text: "Requêtes MCO"
      - section: "Formations SSR"
        contents:
          - href: formations/pmsi_ssr_requete.qmd
            text: "Requêtes SSR"
  page-footer:
    left: "Blog codé avec [Quarto](https://quarto.org/)"
    right: "[Mentions légales](../about.html) | &copy; Copyright 2023 - DATAMIS"
    
format:
  html:
    theme: 
      - cosmo
      - style.css
    toc: true
