project:
  type: website

website:
  title: "Data PMSI"
  description: "Codes et formations R pour les PMSI MCO, SMR, PSY et HAD"
  site-url: https://www.datapmsi.com
  navbar:
    background: "#447099"
    left: 
      - href: formation.qmd
        text: "Formations PMSI R"
      - href: prestation.qmd
        text: "Live coding PMSI R"
      - href: guide_post.qmd
        text: "Guide des scripts"
      - href: base_R.qmd
        text: "Pre-requis R"
    right: 
      - text: "Jeux de données"
        menu:
          - href: "dataset_mco.qmd"
            text: "Jeux PMSI MCO"
      - icon: github
        href: https://github.com/denisGustin/datapmsi
  sidebar: 
    style: docked
    contents: 
      - href: formation.qmd
        text: "Formations PMSI R"
      - href: prestation.qmd
        text: "Live coding PMSI R"
      - href: guide_post.qmd
        text: "Guide des scripts"
      - href: scripts_mco.qmd
        text: "Scripts MCO"
      - href: scripts_smr.qmd
        text: "Scripts SMR"
      - href: scripts_psy.qmd
        text: "Scripts PSY"
  page-footer:
    left: "Blog codé avec [Quarto](https://quarto.org/)"
    right: "[Mentions légales](../about.html) | &copy; Copyright 2023-2024 - DATAMIS"
    
format:
  html:
    theme: 
      - cosmo
      - style.css
    toc: true
    toc-location: "left"
