---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Formations PMSI R</span>"
lang: fr
---

::: {.callout-tip}
## Formation "Fichiers PMSI en dataframe R"  

Produire des dataframe R à partir des fichiers du PMSI pour analyser, en toute autonomie, le PMSI de mes établissements avec R  

**Vendredi 6 décembre 2024 de 9h à 12h30**
:::

## Objectifs  

**1|** Apprendre à manipuler les fichiers normalisés de production du PMSI (rss, rsa, rhs, fichcomp, Visual Valo, ...) au format texte ou csv en R pour produire des data frames de données exploitables en analyse PMSI.  

**2|** Etre autonome dans la manipulation des fichiers PMSI en R  

## Programme  

### Rappel R et PMSI (30 minutes)  

Les packages et fonctions du Tidyverse utiles pour manipuler les fichiers PMSI  

Import d'un fichier FICIUM en dataframe/tibble  

Manipulations élémentaires de variables PMSI  

### Import de fichiers PMSI à longueur fixe  (30 minutes)  

Démarche générique d'imports des fichiers PMSI  

Script générique commenté d'import des fichiers PMSI à longueur fixe  

Exemples : fichiers FICHCOMP DMI, partie fixe d'un fichier RSS, partie fixe d'un fichier RHS, fichier Visual Valo séjours  

### Nettoyage et enrichissement (1 heure)  

Normalisation des variables  

Nettoyage des variables post-import  

Enrichissement : libellés et données OVALIDE  

### Pause (15 minutes)  

### Import des fichiers PMSI à longueur variable (45 minutes)  

Script d'import complet d'un fichier RSS dans une list de tibbles (rum, das, dad, ccam)  

Généralisation : RHS, RSA, RPS, ...  

### Séance Questions/Réponses (30 minutes)  

## Pré-requis  

Maîtrise du PMSI, des formats et des logiques des fichiers de production du PMSI  

Manipulations de base en R avec le Tidyverse  

Environnement de travail avec un IDE R : R Studio ou VS Code  

## Méthodologie  

La formation se déroule selon les principes du live coding : [explications](prestation.qmd)  

Les scripts sont exécutés avec des fichiers textes de quelques lignes, conçus par nos soins, au format ATIH 2024.  

Le livrable de la formation est un fichier de code R avec l'ensemble des scripts et exercices de la formation.  

## Formateur  

La formation est conçue et animée par denis Gustin, ingénieur, concepteur et développeur de PMSISoft, logiciel d’analyse PMSI développé principalement en R.  
Il est spécialiste en données PMSI avec plus de 15 ans d’expérience dans les différents PMSI et intervient régulièrement, en tant que formateur et consultant, dans des établissements de santé sur des problématiques d’analyses PMSI et de données de santé.  

Il développe et maintient le package R de données PMSI [refpmsi::](https://denisgustin.github.io/refpmsi/index.html){target="_blank"}.  

Il anime le blog [lespmsi.com](https://www.lespmsi.com){target="_blank"}  

## Tarif de la formation   

400€ / personne sous convention de formation  

## Pré-inscription  

[Pré-inscription](https://www.lespmsi.com/contact-pmsisoft){target="_blank"} en sélectionnant l'objet "Formation Fichiers PMSI en dataframe R"   

A réception de votre demande de pré-inscription nous vous recontacterons pour :  
1| valider avec vous votre inscription  
2| communiquer la convention de formation  
3| communiquer les conditions générales de vente (CGV)  
4| communiquer le règlement intérieur de la formation  
