---
title: "Packages et fonctions R des formations Data PMSI avec R"
lang: fr
---

## Formation Requêtes MCO

Liste quasi exhaustive des packages et fonctions R utilisés dans la formation.

**Fonctions R de base** : all(), any(), as.Date(), cumsum(), ifelse(), is.na(), match(), readRDS(), sum(), which()

Package **dplyr** : across(), add_count(), arrange(), case_when(), count(), cur_data(), distinct(), filter(), first(), full_join(), glimpse(), group_by(), if_all(), if_any(), inner_join(), lag(), last(), lead(), left_join(), mutate(), n(), n_distinct(), pull(), relocate(), right_join(), row_number(), rowwise(),  select(), semi_join(), slice(), summarise(),

Package **tidyr** : complete(), drop_na(), pivot_longer(), pivot_wider(), unite()

Package **stringr** : str_c(), str_detect(), str_extract(), str_sub(), str_unique()

Package **readr** : read_csv(), read_csv2(), read_delim(), write.csv(), write.csv2()

Package **lubridate** : ymd()

Package **tibble** : enframe(), tibble()

Package **tidyselect** : all_of(), any_of(), contains(), ends_with(), everything(), starts_with(), where()

Package **jsonlite** : fromJSON(), toJSON()

package **data.table** : rleid(), uniqueN()

Package **refpmsi** : refpmsi()

## Formation Requêtes MCO [Avancé]

A venir