---
title: "Pédagogie"
lang: fr
---

# Principes pédagogiques

## Constats et objectifs

La pédagogie des formations **Data PMSI avec R** est conçue et adaptée aux constats et objectifs suivants : 

- les participants sont des professionnels du PMSI ou liés au PMSI. Ils maîtrisent le PMSI.  

- les participants disposent d'un environnement de travail R et ont déjà, à minima, coder quelques lignes en R (Voir [Pré-requis R](base_R.qmd))  

- les participants sont familiers des requêtes et analyses PMSI  

- les participants cherchent à devenir autonomes dans leurs travaux quotidiens d'analyses du PMSI avec R  

- les participants attendent une vision claire des types d'analyses possibles, en fonction de leur montée en compétence progressive des codes de manipulations des données PMSI avec R  

- les participants attendent de pratiquer, de bout en bout (des données brutes PMSI aux résultats d'analyse), des analyses PMSI avec R  

- les participants sont intéressés à disposer d'un ensemble de scripts PMSI en R qu'ils pourront reproduire, décliner et approfondir sur les données PMSI de leurs établissements  

## Démarche  

La démarche principale des formations **Data PMSI avec R** consiste à partir de situations d'analyses PMSI issues du terrain pour les coder en R et, ainsi, apprendre et pratiquer la grammaire R nécessaire mais juste suffisante, pour réaliser les analyses voulus.  

Chaque formation **Data PMSI avec R** est conçue de manière graduée pour introduire à chaque nouvelle analyse, des codages R de plus en plus complexes en lien avec l'objectif de la formation (requêtes, scripts, tableaux, graphiques).

Chaque formation **Data PMSI avec R** est donc constituée d'une suite de modules qui permettent de réaliser des analyses PMSI de plus en plus complexes.

Le dispositif des formations s'articule autour de séances de live coding à partir de jeux de données PMSI réalistes, d'exercices à réaliser par les participants avec correction du formateur et de mise à disposition de scripts R documentés.  

## Live coding en direct

Le live coding en direct consiste, pour le formateur, à écrire et commenter le code à haute voix pendant qu'il enseigne le pourquoi et les caractéristiques du code en train de s'écrire. 

Le formateur explique les différents éléments et principes pertinents pour que les apprenants comprennent le code.  

Les participants sont invités, dans le même temps, à écrire et à  exécuter le même code sur leur poste de travail.  

Dans cette opération, les participants assimilent le codage  et recontrent leurs éventuels points de douleur (= les enchaînements de code qui leur paraissent bizarres ou incompréhensibles). Ils sollicitent alors le formateur pour comprendre et progresser en direct.  

Une séquence de live coding en direct dure de quelques minutes à 30 minutes maximum. Elle est généralement composée de 3 phases :  

- exposé de la problématique PMSI et de l'algorithmique permettant, à partir d'un ensemble de données PMSI brutes ou déjà retravaillées, d'arriver au résultat voulu.  

- codage R en direct par le formateur avec les participants qui reproduisent le codage en direct. Le formateur commente le codage en direct avec d'éventuels aller-retours dans le script en cours de codage et des apartés techniques.  

- temps de débrief avec les participants : alternatives de codage R, **retours d'expérience du formateur**, réponses aux questions des participants.  

Un module d'1h30 est ainsi généralement constitué d'une dizaine de séquences.

Pour aller plus loin : [Papier "Ten quick tips for teaching with participatory live coding"](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008090){target="_blank"}

## Exercices 

Chaque journée de formation est ponctuée d'exercices, mis à disposition des participants. 

Un exercice comprend une problématique PMSI, des indications de résolution et, le plus souvent, sur la base des jeux de données fournis, le résultat attendu : il est attendu que le participant compose le codage R pour parvenir au résultat. 

Les corrections d'exercices sont fournies aux participants soit lors de la 2eme journée de formation du programme (pour les formations de 2 journées), soit quelques jours après la formation (pour les formations d'une journée).  

## Documentation

La documentation est constituée de scripts R documentés directement dans le code qui peuvent être repris par les participants à l'issue de chaque formation.  

La documentation est envoyée aux participants, en même temps que les corrections d'exercices, à l'issue de la formation.  

Des liens vers des ressources open souce sont régulièrement proposés pour les aspects strictement R de la formation.    

# Déroulé des formations

## Avant la formation

Les participants lisent, réalisent et valident les pré-requis PMSI et [pré-requis R](base_R.qmd) de la formation.  

Les participants répondent au questionnaire d’auto-évaluation qui leur ait envoyé avant la formation.  

Les participants font le point sur les analyses PMSI qu'ils souhaient coder en R.  

## Pendant la formation

Chaque journée des formations **Data PMSI avec R** est constituée de 4 modules en ligne, 2 le matin et 2 l'après-midi. 

Chaque module est divisé en séquences de live coding en direct (voir rubrique ci-dessus).

Les temps de pause et d'échanges permettent au formateur de répondre aux questions des participants et de reprendre, si nécessaire, certains points du module précédent.  

En fin de journée, les exercices (voir rubrique ci-dessus) sont exposés et envoyés aux participants.  

## Après la formation

Une évaluation à chaud est envoyée aux participants à l'issue de chaque formation.  

La correction des exercices est envoyée aux participants quelques jours après la formation.  

# Etat d'esprit  

Le rythme des formations **Data PMSI R avec R** est soutenu. Ces formations s'adressent à des professionnels entraînés, à l'aise avec un exercice intellectuel prolongé.  

Les formations **Data PMSI avec R** s'adressent à plusieurs participants (de 3 à 10). Chaque participant s'engage, dans ses échanges avec le formateur, à un effort de conceptualisation et de généralisation, pour que la réponse du formateur à ses questions bénéficie à tous les participants.  

Plus généralement, le formateur et les participants partagent une approche exigeante, curieuse et ouverte des problématiques traitées.  

[Contactez-nous pour toute question](https://www.lespmsi.com/contact-pmsisoft){target="_blank"} (avec l'objet "Question formation Data PMSI avec R")  
