---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Live coding PMSI R</span>"
lang: fr
---

## Principes du Live coding PMSI R  

Le live coding consiste, pour un specialiste (ingénieur, data analyst, médecin DIM), à écrire et/ou commenter en direct du code PMSI R dans l'environnement de développement R de son interlocuteur. 

Le spécialiste explique en direct le pourquoi et les caractéristiques du code qu'il est en train de d'écrire.  

Il répond en direct aux questions de son interlocuteur.  

Il teste en direct les scripts codés.  

Il redirige son interlocuteur vers des ressources pertinentes (support formation, codes, packages, documentation).  

Le livrable d'une session de Live coding est constitué par le code écrit et documenté lors de la session et par les éventuelles notes prises par l'interlocuteur.  

Avantage reconnu du Live coding : intervention du spécialiste "au bon moment" pour le "bon problème", directement sur le code de l'interlocuteur  

Pour aller plus loin : [Papier "Ten quick tips for teaching with participatory live coding"](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008090){target="_blank"}

## Exemples de sujets  

Liste non exhaustive :

* codage de scripts répondant à des problématiques de l'interlocuteur  
    + requêtes détection atypies ou contrôles qualité  
    + casemix personnalisés  
    + production en routine d'indicateurs  
    + mise en tibbles des fichiers du .in ou du .out  
    + requêtes détection atypies ou contrôles qualité  
    + récupération/nettoyage et exploitation d'export JSON ou csv OVALIDE  
    + imports de sources de données zip, csv, txt, JSON, ...  
    + graphiques  
    + construction de rapports ad'hoc ou automatisés en routine avec Quarto  
    + etc ...  

* nettoyage de scripts de l'interlocuteur : normalisation, optimisation, documentation, bonnes pratiques  

* audit de code PMSI R ou de sources de données PMSI   

* debugage de scripts  

* formation PMSI R tout niveau  

## Expert PMSI R  

Les séances de Live coding sont réalisées par denis Gustin, ingénieur, concepteur et développeur de PMSISoft, logiciel d’analyse PMSI développé principalement en R.  
Il est spécialiste en données PMSI avec plus de 15 ans d’expérience dans les différents PMSI et intervient régulièrement, en tant que formateur et consultant, dans des établissements de santé sur des problématiques d’analyses PMSI et de données de santé.  

Il développe et maintient le package R de données PMSI [refpmsi::](https://denisgustin.github.io/refpmsi/index.html){target="_blank"}.  

Il anime le blog [lespmsi.com](https://www.lespmsi.com){target="_blank"}  

## Mise en oeuvre  

L'interlocuteur a identifié une ou plusieurs problématiques PMSI R, ponctuelles ou récurrentes.  

L'interlocuteur nous contacte en choisissant un nombre d'heures (engagement minimum : 2 heures), en exposant succinctement sa problématique et en proposant un ou 2 créneaux pour une session.  

**[Réservation session PMSI R](https://www.lespmsi.com/contact-live-coding-pmsi-r)**  

Nous répondons sous 24 heures (validation[^1], demande de précision, contre-proposition éventuelle de créneaux).  

Les sessions se font via Zoom : nous envoyons un lien de connexion en début de session.  

Chacune de nos interventions se fait avec l'accord et sous le contrôle du médecin DIM et de la politique de gestion des données de l'établissement.  

Les sessions de Live coding sont des prestations d'engagement de moyens, correspondant au temps d'expertise des sessions.  

## Tarif Live coding PMSI R  

150€ HT / heure  

## Autres prestations  

Au cas par car, nous pouvons réaliser des formations PMSI R pour un établissement ou un regroupement d'établissements. Dans ce cadre, via un entretien amont, nous personnalisons les exercices et les exemples au contexte du ou des établissements.  

[Contact](https://www.lespmsi.com/contact-pmsisoft){target="_blank"} (avec l'objet "Question formation Data PMSI avec R")

## Etat d'esprit  

Le rythme des sessions de Live coding ou de formations PMSI R est soutenu. Elles s'adressent à des professionnels entraînés, à l'aise avec un exercice intellectuel prolongé.  

L'export et les interlocuteurs partagent une approche exigeante, curieuse et ouverte des problématiques traitées.  

[^1]: nous nous laissons le droit de ne pas donner suite à une demande.  