---
title: "<b>Casemix nombre d'actes ambulatoires et patients par (journée, patient)</b>"
date: "2025-10-12"
categories: [PSY,RAA]
page-layout: full
---

## Introduction  

Pour chaque couple (journée, patient), calcul du nombre d'actes ambulatoires codés.  

Puis mise en casemix, selon le nombre d'actes par (journée, patient) rencontré, avec pour chacune de ces situations, le calcul du nombre d'actes ambulatoires concernés, le nombre de patients différents concernés et le pourcentage représenté par le nombre d'actes par rapport au total des actes.  

Les journées sont identifiées via la variable `date_acte` et les patients via la variable `no_ipp`  

Ce casemix permet ainsi de répondre à des questions comme celles-ci :  
1| Quelle est la part des actes ambulatoires codés 1 seule fois par (journée, patient) ?  
2| Combien d'actes ambulatoires sont-ils codés dans des situations de 2 actes par (journée, patient) ?  
3| Quel est le nombre de patients ayant bénéficié au moins 1 journée de 5 actes dans une journée ?  
4| Y-a-t-il des situations avec >= 15 actes codés pour un patient ? (cf motif d'exclusion de la DFA)  

## Code  

```{r}
#| label: code
library(dplyr)

casemix_nb_actes_same_day <- psy_raa$raa |> 
    dplyr::select(no_ipp,date_acte) |> 
    dplyr::summarise(.by = c(no_ipp,date_acte),
                     categorie_acte_same_ipp_date = dplyr::n()
                     ) |> 
    dplyr::summarise(.by = categorie_acte_same_ipp_date,
                     nb_categorie_acte_same_ipp_date = dplyr::n(),
                     nb_ipp_same_ipp_date = dplyr::n_distinct(no_ipp, na.rm = TRUE)
                     ) |> 
    dplyr::mutate(nb_acte_categorie_acte_same_ipp_date = sum(nb_categorie_acte_same_ipp_date*categorie_acte_same_ipp_date),
                  percent_categorie_acte_same_ipp_date = nb_categorie_acte_same_ipp_date/nb_acte_categorie_acte_same_ipp_date) |> 
    dplyr::arrange(categorie_acte_same_ipp_date) |> 
    dplyr::select(categorie_acte_same_ipp_date,nb_categorie_acte_same_ipp_date,percent_categorie_acte_same_ipp_date,
                  nb_ipp_same_ipp_date)
casemix_nb_actes_same_day
```

## Commentaires  

Ligne 3 : `psy_raa$raa` est un tibble des variables RAA. Voir [Guide des scripts - Jeux de données](https://www.datapmsi.com/guide_post#via-pmsisoft-standard) 

Lignes 5-7 : calcul par (journée, patient) du nombre d'actes ambulatoires codés  

Ligne 8 : `.by = c(no_ipp,date_acte)` permet de grouper directement dans le `summarise()` sans avoir à passer par un `group_by()`  

Ligne 10 : l'option `na.rm = TRUE` de `dplyr::n_distinct()` gère les situations où aucun `no_ipp` n'est renseigné  

Ligne 12 : le calcul de `nb_acte_categorie_acte_same_ipp_date` comme `sum(nb_categorie_acte_same_ipp_date*categorie_acte_same_ipp_date)` est une manière de faire. Il y en a d'autres.  

Ligne 15-16 : sélection des seules variables intéressantes pour le casemix  

## PMSISoft PSY  

En extrayant la base des RAA à partir de l'écran `Base des RAA`, possibilité de filtrer en amont les RAA (par exemple les seuls actes réalisés par une catégorie professionnelle d'intervenant)  

[PMSISoft PSY](https://www.pmsisoft.com/acces_pmsisoft_psy){target="_blank"}  

[Etre tenu au courant de la publication des nouveaux scripts PMSI R](http://www.lespmsi.com/scripts-pmsi-r/){target="_blank"}  
