---
title: "<b>Rapatriement libellé CIM-10 du DP des RPS</b>"
date: "2024-06-07"
categories: [PSY,RPS,CIM-10]
page-layout: full
---

## Introduction  

Script très simple et très classique pour enrichir les données PMSI via le rapatriement des libellés, ici le libellé CIM-10 du DP de chaque RPS du jeu de données, à partir du référentiel `cim_libelle` [^1]  

## Code  

```{r}
#| label: code
library(dplyr)
library(refpmsi)

cim_libelle <- refpmsi::refpmsi(cim_libelle)

rps_extended <- psy_rps$rps %>% 
    dplyr::select(everything()) %>% 
    dplyr::left_join(cim_libelle %>% dplyr::select(cim_code, dp_libelle = cim_libelle), join_by(dp == cim_code))
rps_extended
```

## Commentaires  

Ligne 6 : `psy_rps$rps` est un tibble des variables de la partie fixe des RPS. Voir [Guide des scripts - Jeux de données](https://www.datapmsi.com/guide_post#via-pmsisoft-standard) 

Ligne 7 : `everything()` est pour `tidyselect::everything()` sachant que le package `tidyselect::` est chargé via le `dplyr`.  
`everything()` dans le `dplyr::select()` est une façon de sélectionner toutes les variables natives du du tibble `psy_rps$rps`, donc toutes les variables de la partie fixe d'un fichier RPS, dont, en particulier, la variable dp  

Ligne 8 : on profite du `dplyr::select()` pour renommer `cim_libelle` en `dp_libelle` plus cohérent.  
Le `dplyr::left_join()` ajoute `dp_libelle` en dernière position  

Dans tous les écrans [PMSISoft PSY](https://www.pmsisoft.com/acces_pmsisoft_psy){target="_blank"}, le libellé des codages CIM-10 est rapatrié par défaut.

[Etre tenu au courant de la publication des nouveaux scripts PMSI R](http://www.lespmsi.com/scripts-pmsi-r/){target="_blank"}  

[^1]: documentation du référentiel [cim_libelle](https://denisgustin.github.io/refpmsi/articles/cim.html#cim-libell%C3%A9){target="_blank"}  
