---
title: "<b>Episodes de soin continu par IPP</b>"
date: "2024-06-11"
categories: [PSY,IPP]
page-layout: full
---

## Introduction  

Pour la définition des épisodes de soin continu en hospitalisation complète, voir [ici](https://www.scansante.fr/sites/default/files/content/376/notice_rme_psy_hospitalisations_longues_en_psychiatrie.pdf){target="_blank"}  

Dans un premier tibble, sur la base des RPS de temps complet, on repère et comptabilise par IPP, les épisodes de soin continu.  

Dans un second tibble, on calcule **par IPP** le nombre de séjours temps complet et le nombre d'épisodes de soin continu.  

## Code  

```{r}
#| label: code
library(dplyr)

vect_fa_temps_complet <- c('01','01D','01S','01P','02','03','04','05','06','07')

rps_episode_soin_continu <- psy_rps$rps %>% 
    dplyr::select(forme_activite,no_ipp,no_sejour,date_debut_sequence,date_fin_sequence,nb_jours_presence) %>% 
    dplyr::filter(forme_activite %in% vect_fa_temps_complet) %>% 
    dplyr::group_by(no_ipp) %>% 
    dplyr::arrange(date_debut_sequence, .by_group = TRUE) %>% 
    dplyr::mutate(same_episode_soin_continu_ipp = as.integer(date_debut_sequence-dplyr::lag(date_fin_sequence, default = date_debut_sequence[1])) <= 1L,
                  cumsum_episode_soin_continu_ipp = cumsum(!same_episode_soin_continu_ipp)+1L,
                  nb_episode_soin_continu_ipp = max(cumsum_episode_soin_continu_ipp)) %>% 
    dplyr::ungroup()
rps_episode_soin_continu

ipp_episode_soin_continu <- rps_episode_soin_continu %>% 
    dplyr::distinct(no_ipp,no_sejour,nb_episode_soin_continu_ipp) %>% 
    dplyr::mutate(.by = no_ipp, nb_sejour_ipp = dplyr::n()) %>% 
    dplyr::distinct(no_ipp,nb_sejour_ipp,nb_episode_soin_continu_ipp)
ipp_episode_soin_continu

```

## Commentaires  

Ligne 3 : le vecteur `vect_fa_temps_complet` correspond aux codes des formes d'activité temps complet  

Ligne 5 : `psy_rps$rps` est un tibble des variables de la partie fixe d'un fichier RPS. Voir [Guide des scripts - Jeux de données](https://www.datapmsi.com/guide_post#via-pmsisoft-standard) 

Ligne 9 : l'argument `.by_group = TRUE` dans le `dplyr::arrange()` permet de trier au sein d'un regroupement.  

Lignes 10 à 12 : codage de l'algorithme de définition d'un épisode de soins continus  

Pour aller + loin :  
Repérage concomitant des épisodes de soin concentré (séquences séparées de 0 à 7 jours dans un même épisode)  
Attribution d'une numérotation aux épisodes de soin continu  
Etc ...

Cette analyse est réalisée dans [PMSISoft PSY](https://www.pmsisoft.com/acces_pmsisoft_psy){target="_blank"} dans l'écran `Séjours > Base des séjours` avec, en particulier, le calcul du nombre d'épisodes de soin continu et du nombre d'épisodes de soin concentré.  

[Etre tenu au courant de la publication des nouveaux scripts PMSI R](http://www.lespmsi.com/scripts-pmsi-r/){target="_blank"}  
