---
title: "<b>Actes CSARR ASS hors préparation ou suivi de dossier</b>"
date: "2025-10-12"
categories: [SMR,CSARR,CSAR]
page-layout: full
---

## Introduction  

Le nouveau CSAR 1R identifie les actes de préparation ou de suivi de dossier via la lettre P en 3eme position (exemple : 11P02 *Préparation et/ou suivi de l'avancement d'un dossier de demande de prestation sociale ou d'une démarche administrative*)[^1]  

Pour repérer les actes ASS hors préparation ou suivi de dossier, nous allons donc successivement :  
1| isoler les actes de préparation ou suivi de dossier en CSARR et CSAR  
2| filtrer les actes réalisés par les Assistant de Service Social (code 62)  
3| repérer les actes qui NE sont PAS des actes de préparation ou de suivi de dossier  
4| enrichir avec les libellés CSARR  

## Code  

```{r}
#| label: code
library(dplyr)
library(refpmsi)

csarr_code <- refpmsi::refpmsi(csarr_code)
csar_transcodage <- refpmsi::refpmsi(csar_transcodage)

csar_transcodage_is_P <- csar_transcodage |> 
    dplyr::mutate(is_acte_csar_P = ifelse(stringr::str_sub(csar_code,3,3) == "P", TRUE, FALSE)) |> 
    dplyr::filter(is_acte_csar_P) |> 
    dplyr::select(csarr_code,csar_code,is_acte_csar_P)

codage_ass_no_preparations_suivi_dossier <- smr_rhs$csarr |> 
    dplyr::select(nas,no_sejour_smr,code_csarr,code_intervenant_csarr) |> 
    dplyr::filter(code_intervenant_csarr == "62") |> 
    dplyr::anti_join(csar_transcodage_is_P, join_by(code_csarr == csarr_code)) |> 
    dplyr::left_join(csarr_code |> dplyr::filter(annee_pmsi == "2025") |> dplyr::distinct(csarr_code, csarr_libelle),
                     join_by(code_csarr == csarr_code))
codage_ass_no_preparations_suivi_dossier
```

## Commentaires  

Lignes 4-5 : rapatriement des référentiels dont on a besoin à partir du package de données PMSI [refpmsi::](https://wwww.refpmsi.com)  

Ligne 7-10 : on créée le tibble des seuls actes CSAR en P  

Ligne 12 : `smr_rhs$csarr` est un tibble des actes CSARR issus des RHS. Voir [Guide des scripts - Jeux de données](https://www.datapmsi.com/guide_post#via-pmsisoft-standard)  

Ligne 15 : `dplyr::ànti_join()`  filtre les actes CSARR qui ne sont pas les actes de préparation ou de suivi de dossier  

Ligne 16 : le code `csarr_code |> dplyr::filter(annee_pmsi == "2025") |> dplyr::distinct(csarr_code, csarr_libelle)` génère un référentiel des libellés CSARR  

## PMSISoft SMR  

On obtient cette liste dans l'écran `Base des actes CSARR` en filtrant `acte_csarr Regex ZGM+105|ZGM+247|ZZE+026|ZZM+066|ZZM+161|ZZM+159|ZZM+143 ET intervenant Est exactement 62`[^2]

[PMSISoft SMR](https://www.pmsisoft.com/acces_pmsisoft_ssr){target="_blank"} 

[Etre tenu au courant de la publication des nouveaux scripts PMSI R](http://www.lespmsi.com/scripts-pmsi-r/){target="_blank"}  

[^1]: [Guide du CSAR](https://www.atih.sante.fr/simplification-du-csarr-guide-de-codage-csar-0){target="_blank"}  

[^2]: le vecteur des actes CSARR de préparation ou de suivi de dossier peut s'obtenir à partir du tibble `csar_transcodage_is_P` via le code : `vect_csarr_preparations_suivi_dossier <- csar_transcodage_is_P |> dplyr::pull(csarr_code) |> paste0(collapse = "|")`
` 