---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Scripts PMSI MCO (1ere partie)</span>"
subtitle: "Journée 1 de la formation Requêtes MCO<br>15:30-17:00"
lang: fr
---


# Contenu du module  

-   Exposé de ce qu'est un script PMSI MCO : 
    -   Quelles différences avec une suite d'instructions ou une requête ?
    -   Exécuter en routine
    -   Documentation
    -   Evolutions, maintenance, cycles de vie
    -   Retours d'expérience en contexte PMSI MCO
-   Etapes de construction d'un script PMSI MCO
-   Exposé et fonctionnement des variables intermédiaires dans un script  

# Exemples

Liste non exhaustive de scripts PMSI codés dans ce module en code living :  

-   Un script classique : construction de la table des codages CIM avec indication de la position de chaque codage
-   Séjours avec au moins 1 codage CIM ou une famille de codages CIM, indépendamment de la position de codage
-   Activité avec codage CCAM d'anesthésie seule
-   Séjours longs selon plusieurs règles (seuil d'un nombre de journées, > 2,5x DMS national, > 2x DMS du GHM dans l'établissement)
-   Pour une racine de GHM, liste des codages DAS de la base nationale non représentés dans l'établissement
-   Liste des séjours T0, T1 et T2
-   Dédoublonnage des codages par séjour
-   File active à partir de l'anohosp ou du vidhosp  

# Packages et fonctions

[Liste de packages et fonctions utilisés dans la formation Requêtes MCO](../package_function_mco.qmd)
