---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Spécificités des données PMSI MCO</span>"
subtitle: "Journée 1 de la formation Requêtes MCO<br>11:00-12:30"
lang: fr
---


# Contenu du module  

-   Revue détaillée des variables PMSI MCO pour R
    -   Règles de nommage des variables
    -   Spécificités des variables RUM, DAS, CCAM, DMI, UCD, VIDHOSP
    -   Volumétrie, performance des scripts
-   Variables character
    -   Exemples et manipulations simples
-   Variables integer et double
    -   Comptage
    -   Calcul de somme, de moyenne
-   Variables date
    -   Manipulations simples
    -   Calcul de durées PMSI
-   Variables logiques
-   Valeurs nulles, vides, NA
-   Travaux classiques sur les variables : import, nettoyage, production de variables intermédiaire, rapatriement de variables issues des référentiels PMSI
-   Bonnes pratiques
-   Export et import JSON, excel, csv
    
# Exemples

Liste non exhaustive de manipulations réalisées dans ce module en code living :  

-   Production des variables CMD, CMKZ, RGHM
-   Identification activité avec DP en Z
-   Production variables mois et année
-   Extrema et moyenne IGS2 sur un périmètre
-   Import fichier source txt ou JSON
-   Export JSON en sortie de script
-   Export csv et excel en sortie de script

# Packages et fonctions

[Liste de packages et fonctions utilisés dans la formation Requêtes MCO](../package_function_mco.qmd)

