---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Produire des case-mix PMSI MCO</span>"
subtitle: "Journée 2 de la formation Requêtes MCO<br>13:30-15:00"
lang: fr
---


# Contenu du module  

-   Les scripts types pour produire des casemix MCO
-   La préparation de données avant la production d'un casemix MCO  
-   Les colonnes de % et de comparaison de périodes  
-   Différents calculs en case mix : comptage, moyenne, médiane, extrema
-   Bonnes pratiques en prévision de l'édition des casemix en tableau ou graphique
-   Le traitement des libellés dans un casemix

# Exemples

Liste non exhaustive d'analyses PMSI codées dans ce module en code living :  

-   Tri d'un casemix en C,M,Z,K selon un ordre prédifini par le médecin DIM
-   Casemix GHM par DMI
-   Casemix d'activité par mois
-   Forcer, pour un mois donné, la présence à 0 séjour d'un GHM représenté dans l'année mais non représenté ce mois donné
-   Regrouper l'activité en dessous d'un seuil dans une catégorie "Autre"
-   Casemix par UM et 6eme position (J,T,1,2,3,4)
-   Casemix des DMS par codage selon leur position
-   Case mix par mode d'entrée, provenance, mode de sortie, destination
-   Calculs selon différentes définitions du nombre de journée en PMSI MCO
-   Case mix des séjours en T (T0, T1 et T2)
-   Fusionner plusieurs colonnes
-   Ajouter une ligne de type "Total"  

# Packages et fonctions

[Liste de packages et fonctions utilisés dans la formation Requêtes MCO](../package_function_mco.qmd)
