---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Requêtes PMSI MCO de base (2eme partie)</span>"
subtitle: "Journée 2 de la formation Requêtes MCO<br>11:00-12:30"
lang: fr
---


# Contenu du module  

-   Exposé et mise en pratique de la notion de flag d'activité PMSI MCO
-   Requêtes du type "au moins n occurrences", "au plus n occurences", "entre n1 et n2 occurrences"   
-   Comment traîter les blocs DAS et CCAM ? quelques manipulations simples en regex

# Exemples

Liste non exhaustive de requêtes PMSI codées dans ce module en code living :  

-   Séjours niveau n avec au moins 1 CMA niveau > n
-   Séjours avec une même famille de codage en DP/DR versus DAS
-   Séjours multi-UM avec passage dans une certaine UM dans le dernier rum
-   Codage post évênement intra-séjour  
-   Extraction des journées sans codage CCAM
-   Calcul du total des journées du séjour rattaché à chaque rum
-   Proportion par rapport à la 1ere valeur d'un regroupement
-   DMS associé à un codage CIM
-   Calculer le nombre d'occurrences à venir d'un codage après une 1ere occurence de codage de ce codage
-   Identification du ou des rum le(s) plus long(s) dans les séjours multi_rum
-   Repérage de séquences journalières consécutives de codage CCAM   
-   Séjours d'au moins 3 jours sans une certaine famille de DAS codé au moins 1 fois  

# Packages et fonctions

[Liste de packages et fonctions utilisés dans la formation Requêtes MCO](../package_function_mco.qmd)
