---
title: "<span style='font-family: Boska; font-size: 2.75rem; font-weight: 800;'>Formation Requêtes MCO - Exemples</span>"
lang: fr
---

::: {.callout-note}
## Prochaines dates
Journée 1 : vendredi 24 mars 2023  
Journée 2 : vendredi 31 mars 2023
:::


# Liste des requêtes MCO codées dans la formation  

## Module [Requêtes PMSI MCO de base (1ere partie)](pmsi_mco_requete_day1_module1.html)

-   Récupération de l'activité d'un regroupement d'UM
-   Calcul du nombre de RUM et de séjours par regroupement C, M, K, Z
-   Codage du controle Qualité OVALIDE "1.Q.1.CC – Nombre de séjours avec confirmation de codage parmi les GHM concernés"
-   Séjours d'une UM type SI ou REA sans IG2 codé ou avec IGS2 en dessous d'un seuil
-   Filtrer une activité par rapport à des dates
-   Séjours avec tous les codages représentés d'un protocole
-   Repérage de passages dans un ou plusieurs UM
-   Calcul de l'âge en années et journées
-   Ne retenir que les >+75 ans entrés par un service donné 

## Module [Spécificités des données PMSI MCO](pmsi_mco_requete_day1_module2.html)

-   Production des variables CMD, CMKZ, RGHM
-   Identification activité avec DP en Z
-   Production variables mois et année
-   Extrema et moyenne IGS2 sur un périmètre
-   Import fichier source txt ou JSON
-   Export JSON en sortie de script
-   Export csv et excel en sortie de script

## Module [Enrichissement des données PMSI MCO](pmsi_mco_requete_day1_module3.html)

-   Rapatriement des libellés CIM-10 pour les DP, DR et DAS  
-   Rapatriement des CMA  
-   Rapatriement informations CCAM à partir du référentiel de la CCAM à usage PMSI  
-   Enrichissement avec informations du FICIUM
-   Rapatriement des GHS et informations liées via les rsa
-   Rapatriement référentiel GHS
-   Pour une racine de GHM, récupération de liste des codages de la base nationale à partir de tableaux [ScanSante](https://www.scansante.fr/)
-   Enrichissement avec les libellés des mois  
-   Thésaurus à partir des listes en -D et en -A du manuel de groupage MCO  

## Module [Scripts PMSI MCO (1ere partie)](pmsi_mco_requete_day1_module4.html)

-   Un script classique : construction de la table des codages CIM avec indication de la position de chaque codage
-   Séjours avec au moins 1 codage CIM ou une famille de codages CIM, indépendamment de la position de codage
-   Activité avec codage CCAM d'anesthésie seule
-   Séjours longs selon plusieurs règles (seuil d'un nombre de journées, > 2,5x DMS national, > 2x DMS du GHM dans l'établissement)
-   Pour une racine de GHM, liste des codages DAS de la base nationale non représentés dans l'établissement
-   Liste des séjours T0, T1 et T2
-   Dédoublonnage des codages par séjour
-   File active à partir de l'anohosp ou du vidhosp  

## Module [Données PMSI MCO "bien rangés" (tidy)](pmsi_mco_requete_day2_module1.html)

-   Eclatement d'une activité par mois avec une colonne par mois
-   Homogénéisation du type de données par colonne
-   Création de colonnes par sévérité  
-   Exemples de traitement classique en "accordéon" en PMSI MCO  

## Module [Requêtes PMSI MCO de base (2eme partie)](pmsi_mco_requete_day2_module2.html)

-   Séjours niveau n avec au moins 1 CMA niveau > n
-   Séjours avec une même famille de codage en DP/DR versus DAS
-   Séjours multi-UM avec passage dans une certaine UM dans le dernier rum
-   Codage post évênement intra-séjour  
-   Extraction des journées sans codage CCAM
-   Calcul du total des journées du séjour rattaché à chaque rum
-   Proportion par rapport à la 1ere valeur d'un regroupement
-   DMS associé à un codage CIM
-   Calculer le nombre d'occurrences à venir d'un codage après une 1ere occurence de codage de ce codage
-   Identification du ou des rum le(s) plus long(s) dans les séjours multi_rum
-   Repérage de séquences journalières consécutives de codage CCAM   
-   Séjours d'au moins 3 jours sans une certaine famille de DAS codé au moins 1 fois  

## Module [Produire des case-mix PMSI MCO](pmsi_mco_requete_day2_module3.html)

-   Tri d'un casemix en C,M,Z,K selon un ordre prédifini par le médecin DIM
-   Casemix GHM par DMI
-   Casemix d'activité par mois
-   Forcer, pour un mois donné, la présence à 0 séjour d'un GHM représenté dans l'année mais non représenté ce mois donné
-   Regrouper l'activité en dessous d'un seuil dans une catégorie "Autre"
-   Casemix par UM et 6eme position (J,T,1,2,3,4)
-   Casemix des DMS par codage selon leur position
-   Case mix par mode d'entrée, provenance, mode de sortie, destination
-   Calculs selon différentes définitions du nombre de journée en PMSI MCO
-   Case mix des séjours en T (T0, T1 et T2)
-   Fusionner plusieurs colonnes
-   Ajouter une ligne de type "Total"  

## Module [Scripts PMSI MCO (2eme partie)](pmsi_mco_requete_day2_module4.html)

-   Tableau de comparaison pour une pathologie des DMS associées à chaque DAS avec les DMS ScanSanté pour cette pathologie
-   Casemix selon thésaurus de codage issus de regroupement de listes de classification en -D 
-   Analyses via thésaurus maison  
-   Repérage des séjours avec une durée de séjour plus proche de la DMS nationale d'un niveau de sévérité plus élevé  
-   Analyses dérivées de tableaux OVALIDE recodés  
-   Calcul valorisation T2A brute des séjours à partir de données rsa rapatriées  
-   Valorisation T2A modulée par attribution de poids aux UM  

# Packages et fonctions

[Liste de packages et fonctions utilisés dans la formation Requêtes MCO](../package_function_mco.qmd)
